global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'caddy'
    static_configs:
      - targets: ['blog_caddy:2019']
        labels:
          instance: 'caddy-blog'

  # 可选：监控 prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 可选：容器/宿主机资源
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['blog_cadvisor:8080']
